"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jdioqu8$0y6!c3l4^!tvgod2zl=9yt@n--9-qo^071#hr&2=g^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False  # Assurez-vous que DEBUG est False en production
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']  # Change '*' par ton vrai domaine en production
# Application definition
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "bemak4178@gmail.com"
EMAIL_HOST_PASSWORD = "twcc awcf ydrs dvgq"


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# OWNER_EMAIL = os.environ.get('lacinakonate93@gmail.com')  # email du propriétaire
# DELIVERY_EMAIL = os.environ.get('bemak4178@gmail.com')  # email du livreur
OWNER_EMAIL = "lacinakonate93@gmail.com"
DELIVERY_EMAIL = "lacinakonate993@gmail.com"


ASGI_APPLICATION = "myproject.asgi.application"

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379")],
#         },
#     },
# }
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
  
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'import_export',  # Ajout du package
    'ckeditor',  # un bibliothèque qui permet d'intégrer CKEditor
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.humanize',   # ✅ AJOUTER CETTE LIGNE
     'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Ajoute cette ligne 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'myproject.urls'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#          'DIRS': [os.path.join(BASE_DIR, 'myapp ', 'templates')],  # Ajouter cette ligne
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'myapp', 'templates')],
        'DIRS': [BASE_DIR / 'templates'],  # 👈 OBLIGATOIRE
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'db_resto',
#         'USER': 'postgres',
#         'PASSWORD': '12345',
#         'HOST': 'localhost',   # ou l'host Render si c'est en ligne
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

 
MEDIA_URL = '/media/'  # URL pour accéder aux fichiers médias
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Dossier où seront stockées les images
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Dossier où les fichiers statiques seront collectés
# Pour servir les fichiers statiques en mode debug désactivé
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

SILENCED_SYSTEM_CHECKS = [
    "ckeditor.W001",
]

JAZZMIN_SETTINGS = {

    # 🔷 TITRES & BRANDING
    "site_title": "MyShop Admin",
    "site_header": "MyShop Dashboard",
    "site_brand": "MyShop",
    "welcome_sign": "Bienvenue sur le tableau de bord MyShop",
    "copyright": "MyShop © 2026",

    # 🔷 LOGO
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "login_logo": "images/logo.png",
    "login_logo_dark": "images/logo.png",

    # 🔷 UI
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # 🔷 TOP MENU
    # "topmenu_links": [
    #     {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
    #     {"name": "Site Web", "url": "/", "new_window": True},
    # ],

    # 🔷 USER MENU
    # "usermenu_links": [
    #     {"model": "auth.user"},
    #     {"name": "Support", "url": "https://wa.me/225XXXXXXXX", "new_window": True},
    # ],
     "topmenu_links": [
        {"name": "Dashboard", "url": "/admin/dashboard/", "permissions": ["auth.view_user"]},
        {"name": "Site Web", "url": "/", "new_window": True},
    ],
    # 🔷 SIDEBAR ICONS
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        "myapp.categories": "fas fa-tags",
        "myapp.commandes": "fas fa-shopping-cart",
        "myapp.produits": "fas fa-box",
        "myapp.fournisseurs": "fas fa-truck",
        "myapp.detailsfournisseurs": "fas fa-info-circle",
        "myapp.homeslide": "fas fa-images",
    },

    # 🔷 ORDER SIDEBAR
    "order_with_respect_to": [
        "myapp",
        "auth",
    ],

    "custom_links": {
        "myapp": [{
            "name": "Statistiques",
            "url": "admin:index",
            "icon": "fas fa-chart-line",
        }]
    },

    # 🔷 FOOTER
    "show_ui_builder": False,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # ⭐ très beau
    "dark_mode_theme": "darkly",

    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-primary",
    "brand_colour": "navbar-primary",

    "sidebar_nav_child_indent": True,
    "sidebar_nav_flat_style": False,
    "sidebar_nav_legacy_style": False,

    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# """
# Django settings for myproject project.
# Production ready (Cloudinary + Whitenoise)
# """

# from pathlib import Path
# import os

# # Base directory
# BASE_DIR = Path(__file__).resolve().parent.parent

# # SECURITY
# SECRET_KEY = os.environ.get(
#     "DJANGO_SECRET_KEY",
#     "django-insecure-change-this-key"
# )

# DEBUG = False

# ALLOWED_HOSTS = ['*']  # Remplace par ton domaine en production

# # Applications
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     # Apps tierces
#     'import_export',
#     'ckeditor',
#     'cloudinary',
#     'cloudinary_storage',

#     # App locale
#     'myapp',
# ]

# # Middleware
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# # URLs
# ROOT_URLCONF = 'myproject.urls'

# # Templates
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'myapp' / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'myproject.wsgi.application'

# # Database (SQLite)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# # Password validators
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]

# # Internationalization
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # =========================
# # STATIC FILES (Whitenoise)
# # =========================
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_STORAGE = (
#     'whitenoise.storage.CompressedManifestStaticFilesStorage'
# )

# # =========================
# # MEDIA FILES (Cloudinary)
# # =========================
# DEFAULT_FILE_STORAGE = (
#     'cloudinary_storage.storage.MediaCloudinaryStorage'
# )

# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
#     'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
#     'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
# }

# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
