# Generated by Django 5.2.7 on 2026-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_commande_payment_remove_commande_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
