# Generated by Django 5.2.7 on 2026-03-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_table_commande_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.table'),
        ),
    ]
