# Generated by Django 5.2.7 on 2026-04-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_commande_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('mobile_money', 'Mobile Money'), ('cash', 'Paiement à la livraison')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('delivered', 'Livrée')], default='pending', max_length=20),
        ),
    ]
