# Generated by Django 5.2.7 on 2026-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_commande_payment_method_commande_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
