# Generated by Django 5.2.7 on 2026-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='payment_method',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
