# Generated by Django 5.2.7 on 2026-04-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_commande_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='categories',
            field=models.ManyToManyField(blank=True, to='myapp.category'),
        ),
        migrations.DeleteModel(
            name='Commande111',
        ),
    ]
