# Generated by Django 5.2.7 on 2026-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_slide_categories_delete_commande111'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
