# Generated by Django 5.2.7 on 2026-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_slide_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Dashboard Caisse', max_length=100)),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisse',
            },
        ),
    ]
