# Generated by Django 5.2.7 on 2026-04-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_caisse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseProxy',
            fields=[
            ],
            options={
                'verbose_name': '💰 Caisse',
                'verbose_name_plural': '💰 Caisse',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.commande',),
        ),
        migrations.CreateModel(
            name='HistoriqueCommandeProxy',
            fields=[
            ],
            options={
                'verbose_name': '📜 Historique commandes',
                'verbose_name_plural': '📜 Historique commandes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.commande',),
        ),
        migrations.AddField(
            model_name='commande',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_commandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
