# Generated by Django 5.2.7 on 2026-04-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_caisseproxy_historiquecommandeproxy_commande_cashier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OPEN_SHIFT', 'Ouverture caisse'), ('CLOSE_SHIFT', 'Fermeture caisse'), ('PAYMENT', 'Encaissement'), ('REFUND', 'Remboursement'), ('UPDATE', 'Modification')], max_length=20)),
                ('commande_id', models.IntegerField(blank=True, null=True)),
                ('amount_before', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('amount_after', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
