# Generated by Django 5.2.7 on 2026-04-27 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cashauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Caisse', 'verbose_name_plural': 'Audit Caisse'},
        ),
        migrations.AlterField(
            model_name='cashauditlog',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
