# Generated by Django 5.2.7 on 2026-04-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_cashshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAuditProxy',
            fields=[
            ],
            options={
                'verbose_name': '🧾 Audit Caisse',
                'verbose_name_plural': '🧾 Audit Caisse',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.cashauditlog',),
        ),
    ]
