# Generated by Django 5.2.7 on 2026-05-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cashauditproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='categories',
            field=models.ManyToManyField(blank=True, to='myapp.category'),
        ),
    ]
