# Generated by Django 5.2.7 on 2026-05-18 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_homeslide_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('ANNULATION', 'Annulation'), ('PAIEMENT', 'Paiement'), ('SUPPRESSION', 'Suppression')], max_length=50)),
                ('amount_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.commande')),
            ],
            options={
                'verbose_name': 'Audit commande',
                'verbose_name_plural': 'Audit commandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
