# Generated by Django 5.2.7 on 2026-05-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auditcommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
